### PR TITLE
Participation analysis

### PR DESCRIPTION
**Pull request by boyombo**

### CODE REVIEW

**Comment by elo80ka** [comment]
The chart starts to look _really_ bad, once the dates you select are more than about a week apart (take a look at the screenshot below). 

participation-analysis-charts

Maybe we should allow the user select only a start date, and automatically calculate a week from that date? What d'you think?

**Comment by boyombo** [comment]
Hi @laurenweinstein what do you think about this? Do we fix the date ranges for the charts or leave it arbitrary ?

**Comment by boyombo** [comment]
I have changed this to skip some dates when rendering if the number of dates > 10. @elo80ka can you have a look at this ?

**Comment by elo80ka** [comment]
Awesome. Looks _way_ better now. 
:shipit:

**Comment by laurenweinstein** [comment]
Hi Bayo,

Let's allow the user to select the date range. This will give states and
LGAs more autonomy in how they choose to run My Voice. (Our recommendation
last pilot was weekly reports, but in the future, users may decide another
frequency is more suitable for them.)

On Wed, Jan 28, 2015 at 2:26 AM, Bayo Opadeyi <notifications@github.com>
wrote:

> Hi @laurenweinstein <https://github.com/laurenweinstein> what do you
> think about this? Do we fix the date ranges for the charts or leave it
> arbitrary ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myvoice-nigeria/myvoice/pull/262#issuecomment-71791980>
> .
>



-- 
Lauren Weinstein
SERVICE DESIGNER
152 West 25th St. 6th Floor | New York, NY 10001 USA
office: +1 212 388 1010 | mobile: +1 973 271 2397
nigeria mobile | +234 814 223 5832, +234 817 128 4124
lauren@reboot.org
www.reboot.org

**Comment by boyombo** [comment]
Hi Lauren,

Sorry I should have mentioned, we have done it like that already :)

On Wed, Jan 28, 2015 at 3:06 PM, laurenweinstein <notifications@github.com>
wrote:

> Hi Bayo,
>
> Let's allow the user to select the date range. This will give states and
> LGAs more autonomy in how they choose to run My Voice. (Our recommendation
> last pilot was weekly reports, but in the future, users may decide another
> frequency is more suitable for them.)
>
> On Wed, Jan 28, 2015 at 2:26 AM, Bayo Opadeyi <notifications@github.com>
> wrote:
>
> > Hi @laurenweinstein <https://github.com/laurenweinstein> what do you
> > think about this? Do we fix the date ranges for the charts or leave it
> > arbitrary ?
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/myvoice-nigeria/myvoice/pull/262#issuecomment-71791980>
>
> > .
> >
>
>
>
> --
> Lauren Weinstein
> SERVICE DESIGNER
> 152 West 25th St. 6th Floor | New York, NY 10001 USA
> office: +1 212 388 1010 | mobile: +1 973 271 2397
> nigeria mobile | +234 814 223 5832, +234 817 128 4124
> lauren@reboot.org
> www.reboot.org
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/myvoice-nigeria/myvoice/pull/262#issuecomment-71839344>
> .
>



-- 
@boyombo
http://bayo.opadeyi.net
A designer knows he has achieved perfection not when there is nothing left
to add, but when there is nothing left to take away.
 --Antoine de Saint-*Exupery*

**Pull request merged**
